---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: web
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: my-storage-class
  hostPath:
    path: /home/docker/web
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: web-web-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: my-storage-class
